// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc5oJZNFji4CncNJN1h1QtNUHxWlHAOwQ',
    appId: '1:1003440114169:web:596f0fd93212bbbaccd528',
    messagingSenderId: '1003440114169',
    projectId: 'greengrocer-60be7',
    authDomain: 'greengrocer-60be7.firebaseapp.com',
    storageBucket: 'greengrocer-60be7.appspot.com',
    measurementId: 'G-3GRXYNLBBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8IVJpyiyoRidSFPcHhUXf7n6W9W9RyY',
    appId: '1:1003440114169:android:e4ece74ca0ec6831ccd528',
    messagingSenderId: '1003440114169',
    projectId: 'greengrocer-60be7',
    storageBucket: 'greengrocer-60be7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbkpfFpw-GwSV13EqOiQ1F8QQyGuR9BeU',
    appId: '1:1003440114169:ios:292d475262a2b9eeccd528',
    messagingSenderId: '1003440114169',
    projectId: 'greengrocer-60be7',
    storageBucket: 'greengrocer-60be7.appspot.com',
    iosClientId: '1003440114169-1dt4fpg87tsc7hc9jcskiv5veief9fts.apps.googleusercontent.com',
    iosBundleId: 'com.example.gstoreAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbkpfFpw-GwSV13EqOiQ1F8QQyGuR9BeU',
    appId: '1:1003440114169:ios:292d475262a2b9eeccd528',
    messagingSenderId: '1003440114169',
    projectId: 'greengrocer-60be7',
    storageBucket: 'greengrocer-60be7.appspot.com',
    iosClientId: '1003440114169-1dt4fpg87tsc7hc9jcskiv5veief9fts.apps.googleusercontent.com',
    iosBundleId: 'com.example.gstoreAdminPanel',
  );
}
